In [2]:
import numpy as np

In [22]:
import cv2

In [15]:
a = np.array([[1,2,3,4],[1,2,3,4]])

In [16]:
mean_a = np.mean(a)
mean_a

2.5

In [17]:
var = a-mean_a

In [18]:
var

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [19]:
np.sum(var*var)/7

1.4285714285714286

In [20]:
np.var(a,ddof=1)

1.4285714285714286

In [23]:
lena_grey = cv2.imread('lena.bmp', cv2.IMREAD_GRAYSCALE)
lena_grey.shape

(512, 512)

In [27]:
jennifer_grey = cv2.imread('jennifer.jpg', cv2.IMREAD_GRAYSCALE)
jennifer_grey_resize = cv2.resize(jennifer_grey, lena_grey.shape)

cv2.namedWindow('origin', cv2.WINDOW_NORMAL)
cv2.imshow('origin', jennifer_grey)
cv2.namedWindow('resized', cv2.WINDOW_NORMAL)
cv2.imshow('resized', jennifer_grey_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
np.mean(jennifer_grey)

115.14023809523809

In [29]:
np.correlate([1, 2, 3], [0, 1, 0.5])

array([3.5])

In [47]:
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])
var_a = np.var(a)
var_b = np.var(b)

np.mean((a-np.mean(a))*(b-np.mean(b)))

0.16666666666666666

In [49]:
np.cov(a.flatten(),b.flatten())

array([[1.  , 0.25],
       [0.25, 0.25]])

In [51]:
(a-np.mean(a))*(b-np.mean(b))

array([0.5, 0. , 0. ])

In [35]:
(a-np.mean(a))*(b-np.mean(b))

array([0.5, 0. , 0. ])

In [118]:
# difining the function, input two gray images and c1,c2, output the structure similarity of two images
def SSIM(A, B, c1, c2):
    mean_A = np.mean(A)
    mean_B = np.mean(B)
    covAB = np.cov(A.flatten(), B.flatten(), ddof=0)[0][1]
    var_A = float(np.cov(A.flatten(), ddof=0))
    var_B = float(np.cov(B.flatten(), ddof=0))
    L = 255
    ans = (2*mean_A*mean_B+(c1*L)**2)*(2*covAB+(c2*L)**2)/((mean_A)**2+(mean_B)**2+(c1*L)**2)/(var_A+var_B+(c2*L)**2)
    return ans

In [120]:
SSIM(lena_grey, jennifer_grey_resize, 1, 1)

0.9348962289197561

In [61]:
a = np.array([1, 2, 3, 4, 6])
print(np.cov(a), np.var(a) * len(a) / (len(a) - 1))

3.7 3.7


In [99]:
np.var(a, ddof=0)

0.05622111167600712

In [100]:
float(np.cov(a, ddof=0))

0.05622111167600712

In [55]:
np.mean((a-np.mean(a))*(a-np.mean(a)))

2.96

In [65]:
import numpy as np
a, b = np.random.rand(2, 4)
print(np.cov(a, b, ddof=0))
print(np.dot(a - np.mean(a), b - np.mean(b)) / len(a) )

[[0.05622111 0.02677895]
 [0.02677895 0.01648918]]
0.0267789513295354


In [86]:
2**2

4

In [85]:
np.cov(a, ddof=0)

array(0.05622111)

In [84]:
np.var(a)

0.05622111167600712

In [80]:
np.cov(lena_grey.flatten(), jennifer_grey_resize.flatten(), ddof=0)[0][1]

365.4204904498765

In [77]:
np.sum(np.multiply(lena_grey-np.mean(lena_grey), jennifer_grey_resize-np.mean(jennifer_grey_resize)))/lena_grey.size

365.4204904498765

In [75]:
lena_grey.size

262144

In [76]:
np.sum(np.multiply(lena_grey-np.mean(lena_grey), jennifer_grey_resize-np.mean(jennifer_grey_resize)).shape

(512, 512)